spring:
  application:
    name: pasarela
  mongodb:
    uri: ${MONGO_URI}
  data:
    redis:
      url: ${REDIS_URI}
      repositories:
        enabled: false
server:
  port: 8081

webclient:
  service-url: http:localhost:8083